
enum OpType { ADD=1, SUB, MUL, DIV, EQ, NE, LT, LE, GT, GE, ASGN }; /*Operator Type*/
enum TokenType { IF_TK=300, THEN_TK, ELSE_TK, WHILE_TK, DO_TK, END_TK, READ_TK, WRITE_TK, ID, ADDOP, MULOP, RELOP, ASGNOP, INTLIT, STRLIT,
		BRACKET_TK, COMM, SEMI_COLUMN  }; /* Tokens Type*/

